# Generated by Django 2.2.28 on 2024-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='character',
            name='clearance_level',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='sector',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
