# Generated by Django 2.2.28 on 2024-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_auto_20240719_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DatabaseEntry',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='bio',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='character',
            name='clearance_level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sector',
        ),
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
