# Generated by Django 2.2.28 on 2024-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_auto_20240722_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
